# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Espb.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EspTester(object):
    def setupUi(self, EspTester):
        EspTester.setObjectName(_fromUtf8("EspTester"))
        EspTester.resize(1754, 1207)
        self.groupBox = QtGui.QGroupBox(EspTester)
        self.groupBox.setGeometry(QtCore.QRect(630, 30, 748, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.splitter = QtGui.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(22, 80, 674, 57))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_6 = QtGui.QLabel(self.splitter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.itfid_edit = QtGui.QLineEdit(self.splitter)
        self.itfid_edit.setObjectName(_fromUtf8("itfid_edit"))
        self.set_dev_list_btn = QtGui.QPushButton(self.splitter)
        self.set_dev_list_btn.setObjectName(_fromUtf8("set_dev_list_btn"))
        self.groupBox_2 = QtGui.QGroupBox(EspTester)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 20, 571, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.splitter_4 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_4.setGeometry(QtCore.QRect(31, 51, 477, 93))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.label_5 = QtGui.QLabel(self.splitter_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.monitorid_edit = QtGui.QLineEdit(self.splitter_2)
        self.monitorid_edit.setObjectName(_fromUtf8("monitorid_edit"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label = QtGui.QLabel(self.splitter_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.comsel_combox = QtGui.QComboBox(self.splitter_3)
        self.comsel_combox.setObjectName(_fromUtf8("comsel_combox"))
        self.com_open = QtGui.QPushButton(self.splitter_3)
        self.com_open.setObjectName(_fromUtf8("com_open"))
        self.layoutWidget = QtGui.QWidget(EspTester)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layoutWidget1 = QtGui.QWidget(EspTester)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(EspTester)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 220, 581, 177))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.splitter_5 = QtGui.QSplitter(self.groupBox_3)
        self.splitter_5.setGeometry(QtCore.QRect(10, 60, 561, 57))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.bc_query_btn = QtGui.QPushButton(self.splitter_5)
        self.bc_query_btn.setObjectName(_fromUtf8("bc_query_btn"))
        self.staquery0_btn = QtGui.QPushButton(self.splitter_5)
        self.staquery0_btn.setObjectName(_fromUtf8("staquery0_btn"))
        self.bwquery0_btn = QtGui.QPushButton(self.splitter_5)
        self.bwquery0_btn.setObjectName(_fromUtf8("bwquery0_btn"))
        self.groupBox_4 = QtGui.QGroupBox(EspTester)
        self.groupBox_4.setGeometry(QtCore.QRect(640, 240, 601, 193))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.splitter_8 = QtGui.QSplitter(self.groupBox_4)
        self.splitter_8.setGeometry(QtCore.QRect(20, 50, 561, 93))
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.splitter_6 = QtGui.QSplitter(self.splitter_8)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.label_2 = QtGui.QLabel(self.splitter_6)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.bcmid_edit = QtGui.QLineEdit(self.splitter_6)
        self.bcmid_edit.setObjectName(_fromUtf8("bcmid_edit"))
        self.splitter_7 = QtGui.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.pushButton = QtGui.QPushButton(self.splitter_7)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.staquery1_btn = QtGui.QPushButton(self.splitter_7)
        self.staquery1_btn.setObjectName(_fromUtf8("staquery1_btn"))
        self.bwquery1_btn = QtGui.QPushButton(self.splitter_7)
        self.bwquery1_btn.setObjectName(_fromUtf8("bwquery1_btn"))
        self.groupBox_5 = QtGui.QGroupBox(EspTester)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 410, 481, 121))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.voltagequery_btn = QtGui.QPushButton(self.groupBox_5)
        self.voltagequery_btn.setGeometry(QtCore.QRect(90, 40, 187, 57))
        self.voltagequery_btn.setObjectName(_fromUtf8("voltagequery_btn"))
        self.groupBox_6 = QtGui.QGroupBox(EspTester)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 730, 1961, 691))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.splitter_10 = QtGui.QSplitter(self.groupBox_6)
        self.splitter_10.setGeometry(QtCore.QRect(40, 320, 120, 30))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.label_4 = QtGui.QLabel(self.splitter_10)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 120, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.send_btn = QtGui.QPushButton(self.groupBox_6)
        self.send_btn.setGeometry(QtCore.QRect(1540, 120, 191, 51))
        self.send_btn.setObjectName(_fromUtf8("send_btn"))
        self.sendedit = QtGui.QLineEdit(self.groupBox_6)
        self.sendedit.setGeometry(QtCore.QRect(220, 100, 1311, 111))
        self.sendedit.setObjectName(_fromUtf8("sendedit"))
        self.recv_edit = QtGui.QLineEdit(self.groupBox_6)
        self.recv_edit.setGeometry(QtCore.QRect(220, 270, 1311, 81))
        self.recv_edit.setObjectName(_fromUtf8("recv_edit"))
        self.groupBox_7 = QtGui.QGroupBox(EspTester)
        self.groupBox_7.setGeometry(QtCore.QRect(640, 450, 1171, 271))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.ibbw_btn = QtGui.QPushButton(self.groupBox_7)
        self.ibbw_btn.setGeometry(QtCore.QRect(60, 180, 187, 57))
        self.ibbw_btn.setObjectName(_fromUtf8("ibbw_btn"))
        self.ibw_btn = QtGui.QPushButton(self.groupBox_7)
        self.ibw_btn.setGeometry(QtCore.QRect(320, 180, 251, 57))
        self.ibw_btn.setObjectName(_fromUtf8("ibw_btn"))
        self.bbw_btn = QtGui.QPushButton(self.groupBox_7)
        self.bbw_btn.setGeometry(QtCore.QRect(640, 180, 187, 57))
        self.bbw_btn.setObjectName(_fromUtf8("bbw_btn"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 40, 187, 57))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_5.setGeometry(QtCore.QRect(660, 110, 187, 57))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_6.setGeometry(QtCore.QRect(900, 110, 187, 57))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 105, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.itfid_set_edit = QtGui.QLineEdit(self.groupBox_7)
        self.itfid_set_edit.setGeometry(QtCore.QRect(137, 40, 131, 57))
        self.itfid_set_edit.setObjectName(_fromUtf8("itfid_set_edit"))
        self.label_8 = QtGui.QLabel(self.groupBox_7)
        self.label_8.setGeometry(QtCore.QRect(490, 50, 195, 30))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.bcmcnt_edit = QtGui.QLineEdit(self.groupBox_7)
        self.bcmcnt_edit.setGeometry(QtCore.QRect(700, 40, 151, 57))
        self.bcmcnt_edit.setObjectName(_fromUtf8("bcmcnt_edit"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 40, 187, 57))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(20, 120, 225, 30))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.setbcmid_edit = QtGui.QLineEdit(self.groupBox_7)
        self.setbcmid_edit.setGeometry(QtCore.QRect(260, 110, 121, 51))
        self.setbcmid_edit.setObjectName(_fromUtf8("setbcmid_edit"))
        self.setbcmid_btn = QtGui.QPushButton(self.groupBox_7)
        self.setbcmid_btn.setGeometry(QtCore.QRect(410, 110, 181, 51))
        self.setbcmid_btn.setObjectName(_fromUtf8("setbcmid_btn"))
        self.groupBox_8 = QtGui.QGroupBox(EspTester)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 560, 541, 151))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.splitter_13 = QtGui.QSplitter(self.groupBox_8)
        self.splitter_13.setGeometry(QtCore.QRect(0, 60, 520, 57))
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName(_fromUtf8("splitter_13"))
        self.sig1_chkBox = QtGui.QCheckBox(self.splitter_13)
        self.sig1_chkBox.setObjectName(_fromUtf8("sig1_chkBox"))
        self.sig2_chkBox = QtGui.QCheckBox(self.splitter_13)
        self.sig2_chkBox.setObjectName(_fromUtf8("sig2_chkBox"))
        self.sig3_chkBox = QtGui.QCheckBox(self.splitter_13)
        self.sig3_chkBox.setObjectName(_fromUtf8("sig3_chkBox"))
        self.pushButton_3 = QtGui.QPushButton(self.splitter_13)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))

        self.retranslateUi(EspTester)
        QtCore.QObject.connect(self.comsel_combox, QtCore.SIGNAL(_fromUtf8("activated(int)")), EspTester.onComSel)
        QtCore.QObject.connect(self.staquery0_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.onSta0BtnClicked)
        QtCore.QObject.connect(self.com_open, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.open)
        QtCore.QObject.connect(self.send_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.send)
        QtCore.QObject.connect(self.monitorid_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnMonitorIDChange)
        QtCore.QObject.connect(self.itfid_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnItfIDChange)
        QtCore.QObject.connect(self.set_dev_list_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnSetDevListBtn)
        QtCore.QObject.connect(self.bc_query_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBcQueryBtnDown)
        QtCore.QObject.connect(self.bwquery0_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBWQuery0BtnDown)
        QtCore.QObject.connect(self.bcmid_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnBcmIDChange)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBcQuery1BtnDown)
        QtCore.QObject.connect(self.staquery1_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.onSta1Query1BtnDown)
        QtCore.QObject.connect(self.bwquery1_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBWQuery1BtnDown)
        QtCore.QObject.connect(self.voltagequery_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnVoltageQueryBtnDown)
        QtCore.QObject.connect(self.itfid_set_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnSetItfIDChange)
        QtCore.QObject.connect(self.bcmcnt_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnBcmCntChange)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBcmCNTConfigBtnDown)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnGenSigBtnDown)
        QtCore.QObject.connect(self.setbcmid_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnSetBcmIDChange)
        QtCore.QObject.connect(self.setbcmid_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnSetBcmIDBtnDown)
        QtCore.QObject.connect(self.ibbw_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnSetibBWBtnDown)
        QtCore.QObject.connect(self.ibw_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnSetIBwBtnDown)
        QtCore.QObject.connect(self.bbw_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnSetbBwBtnDown)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnItfIDConfig)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnCheckItfID)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnCheckBcmCnt)
        QtCore.QMetaObject.connectSlotsByName(EspTester)
        EspTester.setTabOrder(self.monitorid_edit, self.comsel_combox)
        EspTester.setTabOrder(self.comsel_combox, self.com_open)
        EspTester.setTabOrder(self.com_open, self.itfid_edit)
        EspTester.setTabOrder(self.itfid_edit, self.set_dev_list_btn)
        EspTester.setTabOrder(self.set_dev_list_btn, self.bc_query_btn)
        EspTester.setTabOrder(self.bc_query_btn, self.staquery0_btn)
        EspTester.setTabOrder(self.staquery0_btn, self.bwquery0_btn)
        EspTester.setTabOrder(self.bwquery0_btn, self.bcmid_edit)
        EspTester.setTabOrder(self.bcmid_edit, self.pushButton)
        EspTester.setTabOrder(self.pushButton, self.staquery1_btn)
        EspTester.setTabOrder(self.staquery1_btn, self.bwquery1_btn)
        EspTester.setTabOrder(self.bwquery1_btn, self.voltagequery_btn)
        EspTester.setTabOrder(self.voltagequery_btn, self.send_btn)

    def retranslateUi(self, EspTester):
        EspTester.setWindowTitle(_translate("EspTester", "Dialog", None))
        self.groupBox.setTitle(_translate("EspTester", "设备列表", None))
        self.label_6.setText(_translate("EspTester", "接口模块ID:", None))
        self.set_dev_list_btn.setText(_translate("EspTester", "设备列表", None))
        self.groupBox_2.setTitle(_translate("EspTester", "全局设置", None))
        self.label_5.setText(_translate("EspTester", "监测模块ID:", None))
        self.label.setText(_translate("EspTester", "串口：", None))
        self.com_open.setText(_translate("EspTester", "打开", None))
        self.groupBox_3.setTitle(_translate("EspTester", "旧版查询", None))
        self.bc_query_btn.setText(_translate("EspTester", "广播查询0", None))
        self.staquery0_btn.setText(_translate("EspTester", "状态查询0", None))
        self.bwquery0_btn.setText(_translate("EspTester", "报文查询0", None))
        self.groupBox_4.setTitle(_translate("EspTester", "新版查询", None))
        self.label_2.setText(_translate("EspTester", "报文传输模块ID:", None))
        self.pushButton.setText(_translate("EspTester", "广播查询1", None))
        self.staquery1_btn.setText(_translate("EspTester", "状态查询1", None))
        self.bwquery1_btn.setText(_translate("EspTester", "报文查询1", None))
        self.groupBox_5.setTitle(_translate("EspTester", "测试电压查询", None))
        self.voltagequery_btn.setText(_translate("EspTester", "电压查询", None))
        self.groupBox_6.setTitle(_translate("EspTester", "串口发送与接收", None))
        self.label_4.setText(_translate("EspTester", "接收  ：", None))
        self.label_3.setText(_translate("EspTester", "生成帧：", None))
        self.send_btn.setText(_translate("EspTester", "发送", None))
        self.groupBox_7.setTitle(_translate("EspTester", "接口模块配置", None))
        self.ibbw_btn.setText(_translate("EspTester", "配置报文", None))
        self.ibw_btn.setText(_translate("EspTester", "接口模块报文", None))
        self.bbw_btn.setText(_translate("EspTester", "应答器报文", None))
        self.pushButton_4.setText(_translate("EspTester", "配置ID", None))
        self.pushButton_5.setText(_translate("EspTester", "查询接口ID", None))
        self.pushButton_6.setText(_translate("EspTester", "查询BCM个数", None))
        self.label_7.setText(_translate("EspTester", "接口ID:", None))
        self.label_8.setText(_translate("EspTester", "传输模块个数:", None))
        self.pushButton_2.setText(_translate("EspTester", "配置BCM个数", None))
        self.label_9.setText(_translate("EspTester", "报文传输模块ID:", None))
        self.setbcmid_btn.setText(_translate("EspTester", "配置BCM ID", None))
        self.groupBox_8.setTitle(_translate("EspTester", "信号切换", None))
        self.sig1_chkBox.setText(_translate("EspTester", "sig1", None))
        self.sig2_chkBox.setText(_translate("EspTester", "sig2", None))
        self.sig3_chkBox.setText(_translate("EspTester", "sig3", None))
        self.pushButton_3.setText(_translate("EspTester", "生成", None))

