# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Esp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EspTester(object):
    def setupUi(self, EspTester):
        EspTester.setObjectName(_fromUtf8("EspTester"))
        EspTester.resize(1024, 720)
        self.groupBox = QtGui.QGroupBox(EspTester)
        self.groupBox.setGeometry(QtCore.QRect(540, 20, 470, 120))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 40, 467, 59))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.itfid_edit = QtGui.QLineEdit(self.widget)
        self.itfid_edit.setObjectName(_fromUtf8("itfid_edit"))
        self.horizontalLayout_3.addWidget(self.itfid_edit)
        self.set_dev_list_btn = QtGui.QPushButton(self.widget)
        self.set_dev_list_btn.setObjectName(_fromUtf8("set_dev_list_btn"))
        self.horizontalLayout_3.addWidget(self.set_dev_list_btn)
        self.groupBox_2 = QtGui.QGroupBox(EspTester)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 515, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.widget1 = QtGui.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(11, 41, 461, 40))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.monitorid_edit = QtGui.QLineEdit(self.widget1)
        self.monitorid_edit.setObjectName(_fromUtf8("monitorid_edit"))
        self.horizontalLayout.addWidget(self.monitorid_edit)
        self.widget2 = QtGui.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(10, 90, 467, 41))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.widget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.comsel_combox = QtGui.QComboBox(self.widget2)
        self.comsel_combox.setObjectName(_fromUtf8("comsel_combox"))
        self.horizontalLayout_2.addWidget(self.comsel_combox)
        self.com_open = QtGui.QPushButton(self.widget2)
        self.com_open.setObjectName(_fromUtf8("com_open"))
        self.horizontalLayout_2.addWidget(self.com_open)
        self.layoutWidget = QtGui.QWidget(EspTester)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layoutWidget1 = QtGui.QWidget(EspTester)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(EspTester)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 182, 491, 101))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.widget3 = QtGui.QWidget(self.groupBox_3)
        self.widget3.setGeometry(QtCore.QRect(20, 40, 451, 40))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.bc_query_btn = QtGui.QPushButton(self.widget3)
        self.bc_query_btn.setObjectName(_fromUtf8("bc_query_btn"))
        self.horizontalLayout_4.addWidget(self.bc_query_btn)
        self.staquery0_btn = QtGui.QPushButton(self.widget3)
        self.staquery0_btn.setObjectName(_fromUtf8("staquery0_btn"))
        self.horizontalLayout_4.addWidget(self.staquery0_btn)
        self.bwquery0_btn = QtGui.QPushButton(self.widget3)
        self.bwquery0_btn.setObjectName(_fromUtf8("bwquery0_btn"))
        self.horizontalLayout_4.addWidget(self.bwquery0_btn)
        self.groupBox_4 = QtGui.QGroupBox(EspTester)
        self.groupBox_4.setGeometry(QtCore.QRect(510, 180, 500, 131))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.widget4 = QtGui.QWidget(self.groupBox_4)
        self.widget4.setGeometry(QtCore.QRect(10, 30, 470, 40))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.widget4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.bcmid_edit = QtGui.QLineEdit(self.widget4)
        self.bcmid_edit.setObjectName(_fromUtf8("bcmid_edit"))
        self.horizontalLayout_5.addWidget(self.bcmid_edit)
        self.widget5 = QtGui.QWidget(self.groupBox_4)
        self.widget5.setGeometry(QtCore.QRect(10, 80, 470, 40))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton = QtGui.QPushButton(self.widget5)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.staquery1_btn = QtGui.QPushButton(self.widget5)
        self.staquery1_btn.setObjectName(_fromUtf8("staquery1_btn"))
        self.horizontalLayout_6.addWidget(self.staquery1_btn)
        self.bwquery1_btn = QtGui.QPushButton(self.widget5)
        self.bwquery1_btn.setObjectName(_fromUtf8("bwquery1_btn"))
        self.horizontalLayout_6.addWidget(self.bwquery1_btn)
        self.groupBox_5 = QtGui.QGroupBox(EspTester)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 300, 212, 100))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.voltagequery_btn = QtGui.QPushButton(self.groupBox_5)
        self.voltagequery_btn.setGeometry(QtCore.QRect(36, 40, 140, 40))
        self.voltagequery_btn.setObjectName(_fromUtf8("voltagequery_btn"))
        self.groupBox_7 = QtGui.QGroupBox(EspTester)
        self.groupBox_7.setGeometry(QtCore.QRect(270, 310, 741, 161))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.widget6 = QtGui.QWidget(self.groupBox_7)
        self.widget6.setGeometry(QtCore.QRect(10, 40, 720, 40))
        self.widget6.setObjectName(_fromUtf8("widget6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.widget6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.itfid_set_edit = QtGui.QLineEdit(self.widget6)
        self.itfid_set_edit.setObjectName(_fromUtf8("itfid_set_edit"))
        self.horizontalLayout_7.addWidget(self.itfid_set_edit)
        self.label_8 = QtGui.QLabel(self.widget6)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.bcmcnt_edit = QtGui.QLineEdit(self.widget6)
        self.bcmcnt_edit.setObjectName(_fromUtf8("bcmcnt_edit"))
        self.horizontalLayout_7.addWidget(self.bcmcnt_edit)
        self.pushButton_2 = QtGui.QPushButton(self.widget6)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.widget7 = QtGui.QWidget(self.groupBox_7)
        self.widget7.setGeometry(QtCore.QRect(10, 100, 720, 40))
        self.widget7.setObjectName(_fromUtf8("widget7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget7)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.widget7)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.setbcmid_edit = QtGui.QLineEdit(self.widget7)
        self.setbcmid_edit.setObjectName(_fromUtf8("setbcmid_edit"))
        self.horizontalLayout_8.addWidget(self.setbcmid_edit)
        self.setbcmid_btn = QtGui.QPushButton(self.widget7)
        self.setbcmid_btn.setObjectName(_fromUtf8("setbcmid_btn"))
        self.horizontalLayout_8.addWidget(self.setbcmid_btn)
        self.groupBox_8 = QtGui.QGroupBox(EspTester)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 480, 601, 90))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.widget8 = QtGui.QWidget(self.groupBox_8)
        self.widget8.setGeometry(QtCore.QRect(20, 40, 567, 59))
        self.widget8.setObjectName(_fromUtf8("widget8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget8)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.sig1_chkBox = QtGui.QCheckBox(self.widget8)
        self.sig1_chkBox.setObjectName(_fromUtf8("sig1_chkBox"))
        self.horizontalLayout_9.addWidget(self.sig1_chkBox)
        self.sig2_chkBox = QtGui.QCheckBox(self.widget8)
        self.sig2_chkBox.setObjectName(_fromUtf8("sig2_chkBox"))
        self.horizontalLayout_9.addWidget(self.sig2_chkBox)
        self.sig3_chkBox = QtGui.QCheckBox(self.widget8)
        self.sig3_chkBox.setObjectName(_fromUtf8("sig3_chkBox"))
        self.horizontalLayout_9.addWidget(self.sig3_chkBox)
        self.pushButton_3 = QtGui.QPushButton(self.widget8)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.groupBox_6 = QtGui.QGroupBox(EspTester)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 580, 971, 141))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.widget9 = QtGui.QWidget(self.groupBox_6)
        self.widget9.setGeometry(QtCore.QRect(40, 40, 651, 40))
        self.widget9.setObjectName(_fromUtf8("widget9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget9)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_3 = QtGui.QLabel(self.widget9)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_10.addWidget(self.label_3)
        self.sendedit = QtGui.QLineEdit(self.widget9)
        self.sendedit.setObjectName(_fromUtf8("sendedit"))
        self.horizontalLayout_10.addWidget(self.sendedit)
        self.send_btn = QtGui.QPushButton(self.widget9)
        self.send_btn.setObjectName(_fromUtf8("send_btn"))
        self.horizontalLayout_10.addWidget(self.send_btn)
        self.widget10 = QtGui.QWidget(self.groupBox_6)
        self.widget10.setGeometry(QtCore.QRect(40, 90, 920, 40))
        self.widget10.setObjectName(_fromUtf8("widget10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget10)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_4 = QtGui.QLabel(self.widget10)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.recv_edit = QtGui.QLineEdit(self.widget10)
        self.recv_edit.setObjectName(_fromUtf8("recv_edit"))
        self.horizontalLayout_11.addWidget(self.recv_edit)
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()
        self.groupBox_7.raise_()
        self.groupBox_8.raise_()
        self.groupBox_6.raise_()

        self.retranslateUi(EspTester)
        QtCore.QObject.connect(self.comsel_combox, QtCore.SIGNAL(_fromUtf8("activated(int)")), EspTester.onComSel)
        QtCore.QObject.connect(self.staquery0_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.onSta0BtnClicked)
        QtCore.QObject.connect(self.com_open, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.open)
        QtCore.QObject.connect(self.send_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.send)
        QtCore.QObject.connect(self.monitorid_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnMonitorIDChange)
        QtCore.QObject.connect(self.itfid_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnItfIDChange)
        QtCore.QObject.connect(self.set_dev_list_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnSetDevListBtn)
        QtCore.QObject.connect(self.bc_query_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBcQueryBtnDown)
        QtCore.QObject.connect(self.bwquery0_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBWQuery0BtnDown)
        QtCore.QObject.connect(self.bcmid_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnBcmIDChange)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBcQuery1BtnDown)
        QtCore.QObject.connect(self.staquery1_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.onSta1Query1BtnDown)
        QtCore.QObject.connect(self.bwquery1_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnBWQuery1BtnDown)
        QtCore.QObject.connect(self.voltagequery_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnVoltageQueryBtnDown)
        QtCore.QObject.connect(self.itfid_set_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnSetItfIDChange)
        QtCore.QObject.connect(self.bcmcnt_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnBcmCntChange)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnIDCNTConfigBtnDown)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnGenSigBtnDown)
        QtCore.QObject.connect(self.setbcmid_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EspTester.OnSetBcmIDChange)
        QtCore.QObject.connect(self.setbcmid_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), EspTester.OnSetBcmIDBtnDown)
        QtCore.QMetaObject.connectSlotsByName(EspTester)
        EspTester.setTabOrder(self.monitorid_edit, self.comsel_combox)
        EspTester.setTabOrder(self.comsel_combox, self.com_open)
        EspTester.setTabOrder(self.com_open, self.itfid_edit)
        EspTester.setTabOrder(self.itfid_edit, self.set_dev_list_btn)
        EspTester.setTabOrder(self.set_dev_list_btn, self.bc_query_btn)
        EspTester.setTabOrder(self.bc_query_btn, self.staquery0_btn)
        EspTester.setTabOrder(self.staquery0_btn, self.bwquery0_btn)
        EspTester.setTabOrder(self.bwquery0_btn, self.pushButton)
        EspTester.setTabOrder(self.pushButton, self.staquery1_btn)
        EspTester.setTabOrder(self.staquery1_btn, self.bwquery1_btn)
        EspTester.setTabOrder(self.bwquery1_btn, self.voltagequery_btn)
        EspTester.setTabOrder(self.voltagequery_btn, self.sendedit)
        EspTester.setTabOrder(self.sendedit, self.send_btn)
        EspTester.setTabOrder(self.send_btn, self.recv_edit)

    def retranslateUi(self, EspTester):
        EspTester.setWindowTitle(_translate("EspTester", "Dialog", None))
        self.groupBox.setTitle(_translate("EspTester", "设备列表", None))
        self.label_6.setText(_translate("EspTester", "接口模块ID:", None))
        self.set_dev_list_btn.setText(_translate("EspTester", "设备列表", None))
        self.groupBox_2.setTitle(_translate("EspTester", "全局设置", None))
        self.label_5.setText(_translate("EspTester", "监测模块ID:", None))
        self.label.setText(_translate("EspTester", "串口：", None))
        self.com_open.setText(_translate("EspTester", "打开", None))
        self.groupBox_3.setTitle(_translate("EspTester", "旧版查询", None))
        self.bc_query_btn.setText(_translate("EspTester", "广播查询0", None))
        self.staquery0_btn.setText(_translate("EspTester", "状态查询0", None))
        self.bwquery0_btn.setText(_translate("EspTester", "报文查询0", None))
        self.groupBox_4.setTitle(_translate("EspTester", "新版查询", None))
        self.label_2.setText(_translate("EspTester", "报文传输模块ID:", None))
        self.pushButton.setText(_translate("EspTester", "广播查询1", None))
        self.staquery1_btn.setText(_translate("EspTester", "状态查询1", None))
        self.bwquery1_btn.setText(_translate("EspTester", "报文查询1", None))
        self.groupBox_5.setTitle(_translate("EspTester", "测试电压查询", None))
        self.voltagequery_btn.setText(_translate("EspTester", "电压查询", None))
        self.groupBox_7.setTitle(_translate("EspTester", "接口模块配置", None))
        self.label_7.setText(_translate("EspTester", "接口ID:", None))
        self.label_8.setText(_translate("EspTester", "传输模块个数:", None))
        self.pushButton_2.setText(_translate("EspTester", "配置ID和个数", None))
        self.label_9.setText(_translate("EspTester", "报文传输模块ID:", None))
        self.setbcmid_btn.setText(_translate("EspTester", "配置BCM ID", None))
        self.groupBox_8.setTitle(_translate("EspTester", "信号切换", None))
        self.sig1_chkBox.setText(_translate("EspTester", "sig1", None))
        self.sig2_chkBox.setText(_translate("EspTester", "sig2", None))
        self.sig3_chkBox.setText(_translate("EspTester", "sig3", None))
        self.pushButton_3.setText(_translate("EspTester", "生成", None))
        self.groupBox_6.setTitle(_translate("EspTester", "串口发送与接收", None))
        self.label_3.setText(_translate("EspTester", "生成帧：", None))
        self.send_btn.setText(_translate("EspTester", "发送", None))
        self.label_4.setText(_translate("EspTester", "接收  ：", None))

