# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Swbp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SwbpTester(object):
    def setupUi(self, SwbpTester):
        SwbpTester.setObjectName(_fromUtf8("SwbpTester"))
        SwbpTester.resize(1161, 782)
        self.groupBox_2 = QtGui.QGroupBox(SwbpTester)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 491, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.com_open = QtGui.QPushButton(self.groupBox_2)
        self.com_open.setGeometry(QtCore.QRect(300, 40, 187, 57))
        self.com_open.setObjectName(_fromUtf8("com_open"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 50, 90, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.m_ComSellineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.m_ComSellineEdit.setGeometry(QtCore.QRect(122, 40, 171, 57))
        self.m_ComSellineEdit.setObjectName(_fromUtf8("m_ComSellineEdit"))
        self.layoutWidget = QtGui.QWidget(SwbpTester)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layoutWidget1 = QtGui.QWidget(SwbpTester)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(SwbpTester)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 300, 301, 100))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.voltagequery_btn = QtGui.QPushButton(self.groupBox_5)
        self.voltagequery_btn.setGeometry(QtCore.QRect(36, 40, 140, 40))
        self.voltagequery_btn.setObjectName(_fromUtf8("voltagequery_btn"))
        self.groupBox_8 = QtGui.QGroupBox(SwbpTester)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 170, 571, 111))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 40, 163, 57))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.splitter_4 = QtGui.QSplitter(self.groupBox_8)
        self.splitter_4.setGeometry(QtCore.QRect(21, 41, 379, 57))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.LeuPwr_chkBox = QtGui.QCheckBox(self.splitter_4)
        self.LeuPwr_chkBox.setObjectName(_fromUtf8("LeuPwr_chkBox"))
        self.BrmPwr_chkBox = QtGui.QCheckBox(self.splitter_4)
        self.BrmPwr_chkBox.setObjectName(_fromUtf8("BrmPwr_chkBox"))
        self.pushButton_3 = QtGui.QPushButton(self.splitter_4)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.groupBox_6 = QtGui.QGroupBox(SwbpTester)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 610, 1141, 141))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.sendedit = QtGui.QLineEdit(self.groupBox_6)
        self.sendedit.setGeometry(QtCore.QRect(173, 30, 741, 43))
        self.sendedit.setObjectName(_fromUtf8("sendedit"))
        self.send_btn = QtGui.QPushButton(self.groupBox_6)
        self.send_btn.setGeometry(QtCore.QRect(940, 30, 187, 43))
        self.send_btn.setObjectName(_fromUtf8("send_btn"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(41, 30, 120, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(41, 85, 120, 30))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.recv_edit = QtGui.QLineEdit(self.groupBox_6)
        self.recv_edit.setGeometry(QtCore.QRect(173, 85, 941, 51))
        self.recv_edit.setObjectName(_fromUtf8("recv_edit"))
        self.m_lineEdit_1 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_1.setGeometry(QtCore.QRect(840, 10, 312, 36))
        self.m_lineEdit_1.setObjectName(_fromUtf8("m_lineEdit_1"))
        self.label_2 = QtGui.QLabel(SwbpTester)
        self.label_2.setGeometry(QtCore.QRect(630, 10, 165, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(SwbpTester)
        self.label_5.setGeometry(QtCore.QRect(630, 60, 165, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.m_lineEdit_2 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_2.setGeometry(QtCore.QRect(840, 60, 312, 36))
        self.m_lineEdit_2.setObjectName(_fromUtf8("m_lineEdit_2"))
        self.label_6 = QtGui.QLabel(SwbpTester)
        self.label_6.setGeometry(QtCore.QRect(630, 110, 195, 30))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.m_lineEdit_3 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_3.setGeometry(QtCore.QRect(840, 110, 312, 36))
        self.m_lineEdit_3.setObjectName(_fromUtf8("m_lineEdit_3"))
        self.label_7 = QtGui.QLabel(SwbpTester)
        self.label_7.setGeometry(QtCore.QRect(630, 160, 195, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.m_lineEdit_4 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_4.setGeometry(QtCore.QRect(840, 160, 312, 36))
        self.m_lineEdit_4.setObjectName(_fromUtf8("m_lineEdit_4"))
        self.label_8 = QtGui.QLabel(SwbpTester)
        self.label_8.setGeometry(QtCore.QRect(630, 210, 195, 30))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.m_lineEdit_5 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_5.setGeometry(QtCore.QRect(840, 210, 312, 36))
        self.m_lineEdit_5.setObjectName(_fromUtf8("m_lineEdit_5"))
        self.label_9 = QtGui.QLabel(SwbpTester)
        self.label_9.setGeometry(QtCore.QRect(630, 260, 195, 30))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(SwbpTester)
        self.label_10.setGeometry(QtCore.QRect(630, 310, 165, 30))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.m_lineEdit_6 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_6.setGeometry(QtCore.QRect(840, 260, 312, 36))
        self.m_lineEdit_6.setObjectName(_fromUtf8("m_lineEdit_6"))
        self.m_lineEdit_7 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_7.setGeometry(QtCore.QRect(840, 310, 312, 36))
        self.m_lineEdit_7.setObjectName(_fromUtf8("m_lineEdit_7"))
        self.label_11 = QtGui.QLabel(SwbpTester)
        self.label_11.setGeometry(QtCore.QRect(630, 360, 195, 30))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.m_lineEdit_8 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_8.setGeometry(QtCore.QRect(840, 360, 312, 36))
        self.m_lineEdit_8.setObjectName(_fromUtf8("m_lineEdit_8"))
        self.label_12 = QtGui.QLabel(SwbpTester)
        self.label_12.setGeometry(QtCore.QRect(630, 410, 181, 30))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.m_lineEdit_9 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_9.setGeometry(QtCore.QRect(840, 410, 312, 36))
        self.m_lineEdit_9.setObjectName(_fromUtf8("m_lineEdit_9"))
        self.pushButton = QtGui.QPushButton(SwbpTester)
        self.pushButton.setGeometry(QtCore.QRect(770, 560, 187, 57))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(SwbpTester)
        self.pushButton_2.setGeometry(QtCore.QRect(970, 560, 187, 57))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_13 = QtGui.QLabel(SwbpTester)
        self.label_13.setGeometry(QtCore.QRect(630, 460, 181, 30))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.m_lineEdit_10 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_10.setGeometry(QtCore.QRect(840, 460, 312, 36))
        self.m_lineEdit_10.setObjectName(_fromUtf8("m_lineEdit_10"))
        self.m_lineEdit_11 = QtGui.QLineEdit(SwbpTester)
        self.m_lineEdit_11.setGeometry(QtCore.QRect(840, 510, 312, 36))
        self.m_lineEdit_11.setObjectName(_fromUtf8("m_lineEdit_11"))
        self.label_14 = QtGui.QLabel(SwbpTester)
        self.label_14.setGeometry(QtCore.QRect(630, 510, 181, 30))
        self.label_14.setObjectName(_fromUtf8("label_14"))

        self.retranslateUi(SwbpTester)
        QtCore.QObject.connect(self.com_open, QtCore.SIGNAL(_fromUtf8("clicked()")), SwbpTester.open)
        QtCore.QObject.connect(self.send_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), SwbpTester.send)
        QtCore.QObject.connect(self.voltagequery_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), SwbpTester.OnVoltageQueryBtnDown)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), SwbpTester.OnGenPwrStaBtnDown)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), SwbpTester.OnReadPwrStaBtnDown)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), SwbpTester.OnRestoreBtnDown)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SwbpTester.OnGenClibraBtnDown)
        QtCore.QMetaObject.connectSlotsByName(SwbpTester)
        SwbpTester.setTabOrder(self.com_open, self.voltagequery_btn)
        SwbpTester.setTabOrder(self.voltagequery_btn, self.sendedit)
        SwbpTester.setTabOrder(self.sendedit, self.send_btn)
        SwbpTester.setTabOrder(self.send_btn, self.recv_edit)

    def retranslateUi(self, SwbpTester):
        SwbpTester.setWindowTitle(_translate("SwbpTester", "Dialog", None))
        self.groupBox_2.setTitle(_translate("SwbpTester", "全局设置", None))
        self.com_open.setText(_translate("SwbpTester", "打开", None))
        self.label.setText(_translate("SwbpTester", "串口：", None))
        self.groupBox_5.setTitle(_translate("SwbpTester", "读取所有电流或电压", None))
        self.voltagequery_btn.setText(_translate("SwbpTester", "查询", None))
        self.groupBox_8.setTitle(_translate("SwbpTester", "电源控制", None))
        self.pushButton_4.setText(_translate("SwbpTester", "读取", None))
        self.LeuPwr_chkBox.setText(_translate("SwbpTester", "LEU", None))
        self.BrmPwr_chkBox.setText(_translate("SwbpTester", "BRM", None))
        self.pushButton_3.setText(_translate("SwbpTester", "设置", None))
        self.groupBox_6.setTitle(_translate("SwbpTester", "串口发送与接收", None))
        self.send_btn.setText(_translate("SwbpTester", "发送", None))
        self.label_3.setText(_translate("SwbpTester", "生成帧：", None))
        self.label_4.setText(_translate("SwbpTester", "接收  ：", None))
        self.label_2.setText(_translate("SwbpTester", "A口总电压：", None))
        self.label_5.setText(_translate("SwbpTester", "A口5V电压：", None))
        self.label_6.setText(_translate("SwbpTester", "C口1.5V电压：", None))
        self.label_7.setText(_translate("SwbpTester", "A口2.5V电压：", None))
        self.label_8.setText(_translate("SwbpTester", "A口3.3V电压：", None))
        self.label_9.setText(_translate("SwbpTester", "A口1.5V电压：", None))
        self.label_10.setText(_translate("SwbpTester", "C口LEU电压：", None))
        self.label_11.setText(_translate("SwbpTester", "C口总电压：", None))
        self.label_12.setText(_translate("SwbpTester", "C口3.3V电压：", None))
        self.pushButton.setText(_translate("SwbpTester", "生成校准", None))
        self.pushButton_2.setText(_translate("SwbpTester", "恢复默认", None))
        self.label_13.setText(_translate("SwbpTester", "A口耗流电压：", None))
        self.label_14.setText(_translate("SwbpTester", "C口5V电压：", None))

